db.transactions.createIndex({ "to": 1, "_id": -1 })
db.transactions.createIndex({ "from": 1, "_id": -1 })
db.tokenTransactions.createIndex({ "from": 1, "_id": -1 })
db.tokenTransactions.createIndex({ "to": 1, "_id": -1 })
db.minedBlocks.createIndex({"miner":1, "block": -1})
db.minedBlocks.createIndex({"block": -1})
db.minedUncles.createIndex({"miner":1, "block": -1})
db.transactions.createIndex({"block":1, "_id": -1})
db.transactions.createIndex({"number":1, "_id": -1})
db.balances.createIndex({"address":1, "_id": -1 })
